# Generated by Django 5.2.8 on 2025-11-09 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("brands", "0003_merge_20251108_2252"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingSession",
            fields=[
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                ("completed_steps", models.JSONField(default=list)),
                ("current_step", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_sessions",
                        to="brands.brand",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboarding_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "onboarding_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingScan",
            fields=[
                (
                    "scan_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("timeout", "Timeout"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("scan_config", models.JSONField(default=dict)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("progress_percentage", models.IntegerField(default=0)),
                ("items_scanned", models.IntegerField(default=0)),
                ("total_items", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("priority", models.IntegerField(default=0)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="onboarding.onboardingsession",
                    ),
                ),
            ],
            options={
                "db_table": "onboarding_scans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingSuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "suggestion_type",
                    models.CharField(
                        choices=[
                            ("pricing", "Pricing"),
                            ("inventory", "Inventory"),
                            ("seo", "SEO"),
                            ("marketing", "Marketing"),
                            ("content", "Content"),
                            ("product", "Product"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("impact_score", models.IntegerField(default=50)),
                ("action_required", models.TextField(blank=True)),
                ("estimated_effort", models.CharField(blank=True, max_length=50)),
                ("implemented", models.BooleanField(default=False)),
                ("dismissed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="onboarding.onboardingscan",
                    ),
                ),
            ],
            options={
                "db_table": "onboarding_suggestions",
                "ordering": ["-impact_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("consent_given", models.BooleanField()),
                ("consent_scope", models.JSONField(default=list)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("revoked", models.BooleanField(default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="onboarding.onboardingsession",
                    ),
                ),
            ],
            options={
                "db_table": "user_consents",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="onboardingsession",
            index=models.Index(fields=["user", "status"], name="onboarding__user_id_507b0c_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingsession",
            index=models.Index(
                fields=["status", "expires_at"], name="onboarding__status_d14974_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingsession",
            index=models.Index(fields=["created_at"], name="onboarding__created_8cb8ae_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingscan",
            index=models.Index(fields=["session", "status"], name="onboarding__session_ed9494_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingscan",
            index=models.Index(fields=["status", "priority"], name="onboarding__status_f85097_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingscan",
            index=models.Index(fields=["celery_task_id"], name="onboarding__celery__ba2e32_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingscan",
            index=models.Index(fields=["created_at"], name="onboarding__created_181411_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingsuggestion",
            index=models.Index(
                fields=["scan", "suggestion_type"], name="onboarding__scan_id_b999f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingsuggestion",
            index=models.Index(
                fields=["priority", "impact_score"], name="onboarding__priorit_f7d497_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userconsent",
            index=models.Index(
                fields=["session", "consent_given"], name="user_consen_session_dfdee9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userconsent",
            index=models.Index(fields=["timestamp"], name="user_consen_timesta_892bf4_idx"),
        ),
    ]
