# Generated by Django 5.2.8 on 2025-11-08 21:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brands",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "brands",
                "ordering": ["-created_at"],
                "unique_together": {("organization", "slug")},
            },
        ),
        migrations.CreateModel(
            name="BrandProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "onboarding_step",
                    models.CharField(
                        choices=[
                            ("mission", "Mission"),
                            ("categories", "Categories"),
                            ("personas", "Personas"),
                            ("tone", "Tone"),
                            ("products", "Products"),
                            ("shopify", "Shopify Connection"),
                        ],
                        default="mission",
                        max_length=50,
                    ),
                ),
                ("completed_steps", models.JSONField(default=list)),
                ("is_onboarding_complete", models.BooleanField(default=False)),
                ("mission", models.TextField(blank=True)),
                ("categories", models.JSONField(default=list)),
                ("personas", models.JSONField(default=list)),
                ("tone_sliders", models.JSONField(default=dict)),
                ("required_terms", models.JSONField(default=list)),
                ("forbidden_terms", models.JSONField(default=list)),
                ("single_sku", models.BooleanField(default=False)),
                ("shopify_store", models.CharField(blank=True, max_length=255)),
                ("shopify_access_token", models.TextField(blank=True)),
                ("shopify_connected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "brand_profiles",
            },
        ),
        migrations.CreateModel(
            name="Pathway",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("default_frameworks", models.JSONField(default=list)),
                ("testing_mode", models.BooleanField(default=False)),
                (
                    "publish_policy",
                    models.CharField(
                        choices=[
                            ("AUTO", "Auto-publish"),
                            ("REVIEW", "Require review"),
                            ("MANUAL", "Manual only"),
                        ],
                        default="REVIEW",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pathways",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "pathways",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Blueprint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.user",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blueprints",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "blueprints",
                "ordering": ["-version"],
                "unique_together": {("brand", "version")},
            },
        ),
    ]
