# Generated by Django 5.2.8 on 2025-11-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='onboarding_step',
            field=models.CharField(
                choices=[
                    ('mission', 'Mission'),
                    ('categories', 'Categories'),
                    ('personas', 'Personas'),
                    ('tone', 'Tone'),
                    ('products', 'Products'),
                    ('shopify', 'Shopify Connection')
                ],
                default='mission',
                max_length=50
            ),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='completed_steps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='is_onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
