# Generated by Django 5.2.8 on 2025-11-08 22:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0002_add_brand_identity_field"),
        ("brands", "0002_add_onboarding_fields"),
    ]

    operations = []
